### ISSUE TITLE
Tkinter does not work

### ISSUE THREAD

**Issue by repanoid** [25077667/standalone-python#5]
Hello there, thank you for your work.
tkinter does not work for me:
$ tar -xf release-3.11-x86_64.tar.gz 
$ ./opt/python/bin/python -m tkinter
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/local/Projects/opt/python/lib/python3.11/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ImportError: Error loading shared library libtk8.6.so: No such file or directory (needed by /home/local/Projects/opt/python/lib/python3.11/lib-dynload/_tkinter.cpython-311-x86_64-linux-musl.so)

**Comment by scc-tw** [comment]
@repanoid Thank you for reporting this issue. Yes, it seems to be a bug, but I presently have no time. Could you help me recompile it with that specific flag? Thanks!

**Comment by repanoid** [comment]
I could help you, but I absolutely don’t know how. Can you explain what to do?

**Comment by scc-tw** [comment]
Hi @repanoid,

Enabling the Tk module in CPython might require some investigation. I vaguely remember encountering a minor compile error when I tried enabling it about a year ago. Since the Tk module wasn't necessary for my use case, I decided to disable it instead.

If you do need to enable it, you might need to resolve a few issues related to its integration. I recommend doing some research to address any potential pitfalls.

Thank you!
